# Generated by Django 5.2.1 on 2025-05-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('official_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('independent', models.BooleanField(default=False)),
                ('google_maps', models.URLField(blank=True, null=True)),
                ('open_street_maps', models.URLField(blank=True, null=True)),
                ('capital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('capital_lat', models.FloatField(blank=True, null=True)),
                ('capital_lng', models.FloatField(blank=True, null=True)),
                ('flag_png', models.URLField(blank=True, null=True)),
                ('flag_svg', models.URLField(blank=True, null=True)),
                ('flag_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('coat_of_arms_png', models.URLField(blank=True, null=True)),
                ('coat_of_arms_svg', models.URLField(blank=True, null=True)),
                ('borders', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameCountryProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.name')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
    ]
