# Generated by Django 4.2.21 on 2025-05-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.TextField(max_length=255),
        ),
    ]
