# Generated by Django 4.2.21 on 2025-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_country_official_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.TextField(),
        ),
    ]
