# Generated by Django 4.2.21 on 2025-05-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_country_official_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
